# Generated by Django 4.2.13 on 2024-06-24 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_task_projectmembership_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
